spring.application.name=tasks-manager-api

# Database
spring.datasource.url=${DATABASE_URL}

# Jwt
jwt.secret=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = false
spring.jpa.open-in-view = false 

