spring.application.name=tasks-manager-api

# Profile active
spring.profiles.active = local

# Jwt
jwt.secret=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = false
spring.jpa.open-in-view = false 

